### - Load in NumPy

In [2]:
import numpy as np
import sys

### - Basics

In [9]:
#1-Dimensional

a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [4]:
#2-Dimensional

b = np.array([[3,4,5,6],[9,0,7,1]])
print(b)

[[3 4 5 6]
 [9 0 7 1]]


In [6]:
#Get dimension

a.ndim

1

In [7]:
#Get shape (Row,Column)

b.shape

(2, 4)

In [10]:
#Get type

a.dtype

dtype('int16')

In [13]:
#Get total size
#a.nbytes = a.size * a.itemsize

a.nbytes

6

In [95]:
#Change type

a = a.astype('int32')
a.dtype

dtype('int32')

### - Accessing, changing specific elements, rows, columns,etc

In [14]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
#Get shape of a

a.shape

(2, 7)

In [18]:
#Get a specific element

a[1,3]

11

In [19]:
#Get a row

a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
#Get a column

a[:,0]

array([1, 8])

In [22]:
#Getting fancy [startindex:endindex:stepsize]

a[0,1:6:2]

array([2, 4, 6])

In [25]:
#Updating a value within the array

a[1,5] = 20

print(a) #As can be seen the value was updated

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [29]:
#Updating a 3-Dimensional array

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(b)
print(b.shape)

b[:,1,:] = [[9,9],[9,9]]

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
[[[1 2]
  [9 9]]

 [[5 6]
  [9 9]]]


### - Initializing different types of arrays

In [31]:
#All 0s matrix

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [71]:
#All 1s matrix [element, row, column]

np.ones((2,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [38]:
#Any other number
#Takes two parameters, the shape, the value

np.full((2,2), 5)

array([[5, 5],
       [5, 5]])

In [41]:
#Any other number (full_like)

np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [43]:
#A matrix of random number
#Remember this does not take a tuple

np.random.rand(4,2)

array([[0.41862811, 0.48977391],
       [0.16098447, 0.47778788],
       [0.75787211, 0.91837334],
       [0.06406044, 0.54819179]])

In [48]:
#Random integer values

np.random.randint(1,7, size=(3,3))

array([[3, 3, 6],
       [5, 1, 3],
       [1, 1, 5]])

In [49]:
#The identity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
#Create a repeating array

arr = np.array([[1,2,3]])

r1 = np.repeat(arr,3,axis=0)

print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [58]:
#Challege:1 create the array shown in the picture

chal_arr = np.ones((5,5))

chal_arr[1:4,1:4] = 0

chal_arr[2, 2] = 9

chal_arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [60]:
#Copying arrays

a = np.array([1,2,3])

b = a.copy()

b[0] = 100

print(a) #Notice here that using the .copy() method prevents the value of a from being changed

print(b)

[1 2 3]
[100   2   3]


### - Basic Mathematics

In [61]:
a = np.array([1,2,3,4])

print(a)

[1 2 3 4]


In [62]:
a+2

array([3, 4, 5, 6])

In [63]:
a-2

array([-1,  0,  1,  2])

In [64]:
a*2

array([2, 4, 6, 8])

In [65]:
a/1

array([1., 2., 3., 4.])

In [66]:
b = np.array([1,0,1,0])

print(b)

[1 0 1 0]


In [67]:
a+b

array([2, 2, 4, 4])

In [68]:
a**2

array([ 1,  4,  9, 16])

In [69]:
#Take the sin of all numbers

np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### - Linear Algebra

In [72]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)


#Matrix multiplication
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [73]:
#Find the determinant

c = np.identity(3)
np.linalg.det(c)

1.0

### - Statistics

In [75]:
stats = np.array([[1,2,3],[4,5,6]])

stats

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
#Use the axis argument to get min by row or column

np.min(stats, axis=0)

array([1, 2, 3])

In [81]:
np.max(stats, axis=1)

array([3, 6])

In [84]:
np.sum(stats, axis=1)

array([ 6, 15])

### - Reorganizing Arrays

In [85]:
before = np.array([[1,2,3,4],[5,6,7,8]])

print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [87]:
after = before.reshape((4,2))

print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [90]:
#Vertical stacks

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [91]:
#Horizontal stacks

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [106]:
#Challenge 2, create the array and index the highlighted portion

chal2_arr = np.arange(1,31).reshape(6,5)

print(chal2_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [107]:
#Get 11,12,16,17

chal2_arr[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [109]:
#Get 2,8,14,20

chal2_arr[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [112]:
#Get 4,5,24,25,29,30

chal2_arr[[0,-2,-1],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])